cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'

brew 'jq'
brew 'readline'
brew 'spark'
brew 'wget'
brew 'direnv'
brew 'git'
brew 'httpie'
brew 'rust'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'tree'
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'telnet'
brew 'remake'
brew 'bat'
brew 'kubernetes-cli'
brew 'stern'

cask 'bettertouchtool'
cask 'flux'
cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'sublime-text'
cask 'postman'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'
cask 'vagrant-manager'
cask 'visual-studio-code'
cask 'virtualbox-extension-pack'
cask 'alfred'
cask 'caffeine'
cask 'docker'
cask 'dropbox'
cask 'command-tab-plus'
cask 'bartender'
cask 'datagrip'
cask 'itsycal'
cask 'kindle'
cask 'iterm2'
cask 'zoomus'
cask 'gitup'
cask 'google-cloud-sdk'


